#GET
GET http://localhost:8087/api/v1/categoria/
Content-Type: application/json
###

#POST
POST http://localhost:8087/api/v1/categoria
Content-Type: application/json

{
    "nome":"Testee 1"
}
###

#PUT
PUT http://localhost:8087/api/v1/categoria
Content-Type: application/json

{
    "id":3,
    "nome":"updateee"
}
###



#DELETE
DELETE http://localhost:8087/api/v1/categoria/1
Content-Type: application/json