#GET
GET http://localhost:8087/api/v1/usuario/
Content-Type: application/json
###
#GET
GET http://localhost:8087/api/v1/usuario/magen87500@marksia.com/cy3tJj#W/authenticate
Content-Type: application/json
###

#POST
POST http://localhost:8087/api/v1/usuario
Content-Type: application/json

{
    "nome": "Lucca",
    "email": "lucca@gmail",
    "senha": "111",
    "acesso": 0
}
###

#PUT
PUT http://localhost:8087/api/v1/usuario
Content-Type: application/json

{
    "idUsuario": 2,
    "nome": "Jose",
    "email": "t@test",
    "senha": "111",
    "acesso": 0
}
###



#DELETE
DELETE http://localhost:8087/api/v1/usuario/2
Content-Type: application/json